### ISSUE TITLE
Helium can't identify country id (API return null) for the hotspots in Isreal West Bank

### ISSUE THREAD

**Issue by eladraviv** [helium/lorawan-h3#11] opened 2022-03-27 13:17 UTC
Hotpots in Israel in the West Bank have a major issue that their country returns null from the Helium API.
https://api.helium.io/v1/hotspots/112J8ZQkwHHC6neA6LtTVyTkqgaEQkBwCpd1idoJUhW57Y3HuQGc

Because country is null, miners cannot assign frequency and can't participate in Proof of Coverage at all.

**Potential reason**
Since this is the West Bank maybe some political reasons are in play and the location is not identified as Israel, but for all things matter at this point this is part of Israel and should be recognize so for any miner to be able to work there.

**Hotspots example**
No country (location is in middle of Israel):
![image](https://user-images.githubusercontent.com/32803952/160283282-2a345877-f2e7-472b-acd9-e0056a833661.png)

With country:
![image](https://user-images.githubusercontent.com/32803952/160283282-2a345877-f2e7-472b-acd9-e0056a833661.png)

**Problematic area**
As described all of the hotspots in the west bank are not being allocated to Israel as they supposed to.
Higher view:
![image](https://user-images.githubusercontent.com/32803952/160283293-a896442f-7a08-4346-8bc0-af532db403ff.png)
Any hotspot on the right side of the red line are not allocated to Israel, even though the entire picture is within border lines.

**Impact**
Helium is growing rapidly in the last couple months in Israel and there are whole cities in the west bank (no matter the ethnic relation) that will be able to participate as the miners will not work with no country allocation.

**Some more examples**
https://explorer.helium.com/hotspots/hex/882db07329fffff
https://explorer.helium.com/hotspots/hex/882db0701bfffff
https://explorer.helium.com/hotspots/hex/882db00837fffff[](https://user-images.githubusercontent.com/32803952/160280657-dc0b5d49-e3f4-4ee9-9fd6-c6d3474f9afa.png)
Curved Ebony Cobra Sensecap dashboard:
![image](https://user-images.githubusercontent.com/32803952/160283300-8d893f7a-3713-49ac-bd86-ec2bd1da1f65.png)

How can we solve this problem for the benefits of everyone?

Thanks,
Elad.

**Comment by eladraviv** [comment] 2022-03-27 13:18
Also opened an issue here:
https://github.com/helium/blockchain-etl/issues/308
Not sure which is the correct repo...

**Comment by madninja** [comment] 2022-03-28 13:51
Duplicate of https://github.com/helium/blockchain-etl/issues/308

**Closed by madninja** 2022-03-28 13:51 UTC
